version: '3'
services:
  inspector-influxdb:
    image: influxdb:1.8
    container_name: inspector-influxdb
    networks:
      - inspectornet
    ports:
      - "8086:8086/tcp"
      - "8087:8087/udp"
    environment:
      # Need to enable influxdb's UDP service because we are using UDP client.
      - INFLUXDB_UDP_DATABASE=inspector
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_UDP_BIND_ADDRESS=0.0.0.0:8087
    volumes:
      - influx-data:/var/lib/influxdb

  inspector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inspector
    networks:
      - inspectornet
    depends_on:
      - inspector-influxdb
    volumes:
      - .:/export

networks:
  inspectornet:
    driver: bridge

volumes:
  influx-data:
