version: '3'
services:
  inspector-influxdb:
    image: influxdb:1.8
    container_name: inspector-influxdb
    networks:
      - inspectornet
    ports:
      - "8086:8086/tcp"
    environment:
      - INFLUXDB_DB=inspector
    volumes:
      - influx-data:/var/lib/influxdb

  inspector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inspector
    networks:
      - inspectornet
    depends_on:
      - inspector-influxdb
    volumes:
      - .:/export

networks:
  inspectornet:
    driver: bridge

volumes:
  influx-data: