const fs = require('fs');

// Get the path to the file with changed files from command line arguments.
// File generated by "$ git diff main --name-only").
const changedFilesPath = process.argv[2];
const changedFiles = fs.readFileSync(changedFilesPath, 'utf8').split('\n').filter(Boolean);

let success = true; 

let logContent = ''; 

changedFiles.forEach(file => {
  if (file === 'config.prod.json') {
    logContent += `\n+ ${file}`; 
  } else {
    success = false;
    logContent += `\n- ${file}`; 
  }
});

if (success) {
  logContent = '## ✅ SUCCESS: All changes are valid.\n\n```diff' + logContent + '\n```';
} else {
  logContent = '## ❌ ERROR: Only "config.prod.json" should be modified.\n\n```diff' + logContent + '\n```';
}

fs.writeFileSync('log.md', logContent);
fs.writeFileSync(process.env.GITHUB_ENV, `success=${success}\n`);