name: Validate config.prod.json

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate JSON schema
      run: |
        echo "🚀 Running Go code to generate schema.json..."
        go run schema/schema.go
      continue-on-error: true

    - name: Install check-jsonschema
      run: pip install check-jsonschema

    - name: Validate config.prod.json
      run: |
        echo "🔍 Validating config.prod.json against schema..."
        check-jsonschema --schemafile=schema.json config.prod.json
      continue-on-error: true

    - name: Upload validation result
      uses: actions/upload-artifact@v3
      with:
        name: validation-result
        path: validation_output.txt

    - name: Add validation result as comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: validation_output.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}