name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check if only config.prod.json was modified
        id: check-only-config
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          if [[ "$CHANGED_FILES" == "config.prod.json" ]]; then
            echo "Only config.prod.json was modified"
            echo "VERIFICATION_MESSAGE=✅ Only config.prod.json was modified." >> $GITHUB_ENV
          else
            echo "Other files were modified"
            echo "VERIFICATION_MESSAGE=❌ Changes detected in the following files:" >> $GITHUB_ENV
            echo "MODIFIED_FILES=$(echo "$CHANGED_FILES" | tr ' ' '\n')" >> $GITHUB_ENV
          fi

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: File Changes Verification
          recreate: false
          message: |
            ${{ env.VERIFICATION_MESSAGE }}
            ${{ env.MODIFIED_FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}