name: Verify Changes

on:
  pull_request:
    branches:
      - killme

permissions:
  pull-requests: write
  contents: read

jobs:
  verify-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Prepare log file
      run: echo "" > log.txt

    - name: Verify changes
      id: check_changes
      run: |
        echo "🔍 Checking modified files against main branch..."
        git diff --name-only origin/main > modified_files.txt
        cat modified_files.txt | tee -a log.txt
        
        if grep -qv '^config.prod.json$' modified_files.txt; then
          echo "❌ Changes detected outside config.prod.json!" | tee -a log.txt
          echo "❌ Verification failed: Changes outside config.prod.json detected." | tee -a log.txt
          exit 1
        else
          echo "✅ Only config.prod.json was modified." | tee -a log.txt
          echo "✅ Verification successful: Only config.prod.json was modified." | tee -a log.txt
        fi

    - name: Add verification result as comment
      if: always()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: log.txt
        header: changes
        header: pull-request2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}