name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get list of changed files
        id: get_changed_files
        uses: tj-actions/changed-files@v37

      - name: Fail if other files are modified
        if: ${{ 
          steps.get_changed_files.outputs.all_modified_files != 'config.prod.json' 
        }}
        run: exit 1

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: changes
          recreate: false
          message: ${{ 
            steps.get_changed_files.outputs.all_modified_files == 'config.prod.json' 
            && '✅ Only config.prod.json was modified.' 
            || '❌ Changes detected in the following files: ' 
            || steps.get_changed_files.outputs.all_modified_files 
          }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}