name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if only config.prod.json was modified
        run: |
          CHANGED_FILES=$(git ls-files -m)
          if [[ "$CHANGED_FILES" == "config.prod.json" ]]; then
            echo "success=true" >> $GITHUB_ENV
            echo "### Verification Result - Success ✅\n**Only \`config.prod.json\` was modified.**" > log.md
          else
            echo "success=false" >> $GITHUB_ENV
            echo "### Verification Result - Failed ❌\nThe following files were modified:\n$CHANGED_FILES" > log.md
          fi

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          header: File Changes Verification
          recreate: false
          path: log.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail the check if necessary
        if: env.success == 'false'
        run: exit 1