name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@v44.5.7

      - name: Check if only config.prod.json was modified
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          if [[ "$CHANGED_FILES" == "config.prod.json" ]]; then
            echo "success=true" >> $GITHUB_ENV
            echo "### Verification Result - Success ✅" > log.md && echo "**Only \`config.prod.json\` was modified.**" >> log.md
          else
            echo "success=false" >> $GITHUB_ENV
            echo "### Verification Result - Failed ❌" > log.md && echo "The following files were modified:" >> log.md
            for file in $CHANGED_FILES; do
              echo "- \`$file\`" >> log.md
            done
          fi

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          header: File Changes Verification
          recreate: false
          path: log.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail the check if necessary
        if: env.success == 'false'
        run: exit 1