name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v1
        id: filter
        with:
          filters: |
            only-config:
              - 'config.prod.json'

      - name: Fail if other files are modified
        if: ${{ steps.filter.outputs.only-config == 'false' }}
        run: exit 1

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: changes
          recreate: false
          message: ${{ steps.filter.outputs.only-config == 'true' && '✅ Only config.prod.json was modified.' || '❌ Changes detected outside config.prod.json!' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
