name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check modified files
        id: check_files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            config:
              - 'config.prod.json'
            others:
              - '*'

      - name: Format list of modified files
        id: format_files
        run: |
          if [ "${{ steps.check_files.outputs.config }}" == 'true' ] && [ "${{ steps.check_files.outputs.others }}" == 'false' ]; then
            echo "message=✅ Only config.prod.json was modified." >> $GITHUB_ENV
          else
            echo "message=❌ Changes detected in the following files:" >> $GITHUB_ENV
            echo "${{ steps.check_files.outputs.all_matched_files }}" | tr ' ' '\n' >> changed_files.txt
            echo "files=$(cat changed_files.txt)" >> $GITHUB_ENV
          fi

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: changes
          recreate: false
          message: |
            ${{ env.message }}
            ${{ env.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
