name: "Check Pull Request Files"
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check modified files
        id: check_files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            config:
              - 'config.prod.json'
            others:
              - '*'

      - name: Add verification result as comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: changes
          recreate: false
          message: ${{ 
            steps.check_files.outputs.config == 'true' && steps.check_files.outputs.others == 'false' && '✅ Only config.prod.json was modified.' || '❌ Changes detected in other files.'
          }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
